# -*- coding:utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Profit(models.Model):
    """利润表"""
    organization_id = models.CharField(_("机构ID"), null=True, blank=True, max_length=32)
    organization_name = models.CharField(_("机构名称"), null=True, blank=True, max_length=128)
    announcement_date = models.DateField(_("公告日期"), null=True)
    begin_date = models.DateField(_("开始日期"), null=True)
    end_date = models.DateField(_("截止日期"), null=True)
    report_year = models.DateField(_("报告年度"), null=True)
    merge_type = models.CharField(_("合并类型"), null=True, blank=True, max_length=128)
    report_source = models.CharField(_("报表来源"), null=True, blank=True, max_length=128)
    yyzsr = models.FloatField(_("营业总收入"), null=True, blank=True)
    qzyysr = models.FloatField(_("其中营业收入"), null=True, blank=True)
    yyzcb = models.FloatField(_("营业总成本"), null=True, blank=True)
    qzyycb = models.FloatField(_("其中营业成本"), null=True, blank=True)
    yysjjfj = models.FloatField(_("营业税金及附加"), null=True, blank=True)
    xsfy = models.FloatField(_("销售费用"), null=True, blank=True)
    glfy = models.FloatField(_("管理费用"), null=True, blank=True)
    ktfy = models.FloatField(_("堪探费用"), null=True, blank=True)
    cwfy = models.FloatField(_("财务费用"), null=True, blank=True)
    zcjzss = models.FloatField(_("资产减值损失"), null=True, blank=True)
    jgyjzbdjsy = models.FloatField(_("加公允价值变动净收益"), null=True, blank=True)
    tzsy = models.FloatField(_("投资收益"), null=True, blank=True)
    qzdlyqyhhyqydtzsy = models.FloatField(_("其中对联营企业和合营企业的投资收益"), null=True, blank=True)
    hdsy = models.FloatField(_("汇兑收益"), null=True, blank=True)
    yxyylrdqtkm = models.FloatField(_("影响营业利润的其他科目"), null=True, blank=True)
    yylr = models.FloatField(_("营业利润"), null=True, blank=True)
    jbtsr = models.FloatField(_("加补贴收入"), null=True, blank=True)
    yywsr = models.FloatField(_("营业外收入"), null=True, blank=True)
    jyywzc = models.FloatField(_("减营业外支出"), null=True, blank=True)
    qzfldzcczss = models.FloatField(_("其中非流动资产处置损失"), null=True, blank=True)
    jyxlrzedqtkm = models.FloatField(_("加影响利润总额的其他科目"), null=True, blank=True)
    lrze = models.FloatField(_("利润总额"), null=True, blank=True)
    jsds = models.FloatField(_("减所得税"), null=True, blank=True)
    jyxjlrdqtkm = models.FloatField(_("加影响净利润的其他科目"), null=True, blank=True)
    jlr = models.FloatField(_("净利润"), null=True, blank=True)
    gsymgssyzdjlr = models.FloatField(_("归属于母公司所有者的净利润"), null=True, blank=True)
    ssgdsy = models.FloatField(_("少数股东损益"), null=True, blank=True)
    mgsy = models.FloatField(_("每股收益"), null=True, blank=True)
    jbmgsy = models.FloatField(_("基本每股收益"), null=True, blank=True)
    xsmgsy = models.FloatField(_("稀释每股收益"), null=True, blank=True)
    qtzhsy = models.FloatField(_("其他综合收益"), null=True, blank=True)
    zhsyze = models.FloatField(_("综合收益总额"), null=True, blank=True)
    qzgsymgs = models.FloatField(_("其中归属于母公司"), null=True, blank=True)
    qzgsyssgd = models.FloatField(_("其中归属于少数股东"), null=True, blank=True)
    lxsr = models.FloatField(_("利息收入"), null=True, blank=True)
    yzbf = models.FloatField(_("已赚保费"), null=True, blank=True)
    sxfjyjsr = models.FloatField(_("手续费及佣金收入"), null=True, blank=True)
    lxzc = models.FloatField(_("利息支出"), null=True, blank=True)
    sxfjyjzc = models.FloatField(_("手续费及佣金支出"), null=True, blank=True)
    tbj = models.FloatField(_("退保金"), null=True, blank=True)
    pfzcje = models.FloatField(_("赔付支出净额"), null=True, blank=True)
    tqbxhtzbjje = models.FloatField(_("提取保险合同准备金净额"), null=True, blank=True)
    bdhlzc = models.FloatField(_("保单红利支出"), null=True, blank=True)
    fbfy = models.FloatField(_("分保费用"), null=True, blank=True)
    qzfldzcczld = models.FloatField(_("其中非流动资产处置利得"), null=True, blank=True)

    class Meta:
        verbose_name = '利润表'
        verbose_name_plural = '利润表管理'


class Assets(models.Model):
    """资产表"""
    organization_id = models.CharField(_("机构ID"), null=True, blank=True, max_length=32)
    organization_name = models.CharField(_("机构名称"), null=True, blank=True, max_length=128)
    announcement_date = models.DateField(_("公告日期"), null=True)
    end_date = models.DateField(_("截止日期"), null=True)
    report_year = models.DateField(_("报告年度"), null=True)
    merge_type = models.CharField(_("合并类型"), null=True, blank=True, max_length=128)
    report_source = models.CharField(_("报表来源"), null=True, blank=True, max_length=128)
    hbzj = models.FloatField(_("货币资金"), null=True, blank=True)
    ygyjzjlqqbdjrdqsydjrzc = models.FloatField(_("以公允价值计量且其变动计入当期损益的金融资产"), null=True, blank=True)
    yspj = models.FloatField(_("应收票据"), null=True, blank=True)
    yszk = models.FloatField(_("应收账款"), null=True, blank=True)
    yfkx = models.FloatField(_("预付款项"), null=True, blank=True)
    qtysk = models.FloatField(_("其他应收款"), null=True, blank=True)
    ysglgsk = models.FloatField(_("应收关联公司款"), null=True, blank=True)
    yslx = models.FloatField(_("应收利息"), null=True, blank=True)
    ysgl = models.FloatField(_("应收股利"), null=True, blank=True)
    ch = models.FloatField(_("存货"), null=True, blank=True)
    qzxhxswzc = models.FloatField(_("其中消耗性生物资产"), null=True, blank=True)
    nndqdfldzc = models.FloatField(_("年内到期的非流动资产"), null=True, blank=True)
    qtldzc = models.FloatField(_("其他流动资产"), null=True, blank=True)
    ldzchj = models.FloatField(_("流动资产合计"), null=True, blank=True)
    kgcsjrzc = models.FloatField(_("可供出售金融资产"), null=True, blank=True)
    cyzdqtz = models.FloatField(_("持有至到期投资"), null=True, blank=True)
    cqysk = models.FloatField(_("长期应收款"), null=True, blank=True)
    cqgqtz = models.FloatField(_("长期股权投资"), null=True, blank=True)
    tzxfdc = models.FloatField(_("投资性房地产"), null=True, blank=True)
    gdzc = models.FloatField(_("固定资产"), null=True, blank=True)
    zjgc = models.FloatField(_("在建工程"), null=True, blank=True)
    gcwz = models.FloatField(_("工程物资"), null=True, blank=True)
    gdzcql = models.FloatField(_("固定资产清理"), null=True, blank=True)
    scxswzc = models.FloatField(_("生产性生物资产"), null=True, blank=True)
    yqzc = models.FloatField(_("油气资产"), null=True, blank=True)
    wxzc = models.FloatField(_("无形资产"), null=True, blank=True)
    kfzc = models.FloatField(_("开发支出"), null=True, blank=True)
    sy = models.FloatField(_("商誉"), null=True, blank=True)
    cqdtfy = models.FloatField(_("长期待摊费用"), null=True, blank=True)
    dysdszc = models.FloatField(_("递延所得税资产"), null=True, blank=True)
    qtfldzc = models.FloatField(_("其他非流动资产"), null=True, blank=True)
    fldzchj = models.FloatField(_("非流动资产合计"), null=True, blank=True)
    zczj = models.FloatField(_("资产总计"), null=True, blank=True)
    dqjk = models.FloatField(_("短期借款"), null=True, blank=True)
    ygyjzjlqqbdjrdqsydjrfz = models.FloatField(_("以公允价值计量且其变动计入当期损益的金融负债"), null=True, blank=True)
    yfpj = models.FloatField(_("应付票据"), null=True, blank=True)
    yfzk = models.FloatField(_("应付账款"), null=True, blank=True)
    yskx = models.FloatField(_("预收款项"), null=True, blank=True)
    yfzgxc = models.FloatField(_("应付职工薪酬"), null=True, blank=True)
    yjsf = models.FloatField(_("应交税费"), null=True, blank=True)
    yflx = models.FloatField(_("应付利息"), null=True, blank=True)
    yfgl = models.FloatField(_("应付股利"), null=True, blank=True)
    qtyfk = models.FloatField(_("其他应付款"), null=True, blank=True)
    yfglgsk = models.FloatField(_("应付关联公司款"), null=True, blank=True)
    nndqdfldfz = models.FloatField(_("年内到期的非流动负债"), null=True, blank=True)
    qtldfz = models.FloatField(_("其他流动负债"), null=True, blank=True)
    ldfzhj = models.FloatField(_("流动负债合计"), null=True, blank=True)
    cqjk = models.FloatField(_("长期借款"), null=True, blank=True)
    yfzq = models.FloatField(_("应付债券"), null=True, blank=True)
    cqyfk = models.FloatField(_("长期应付款"), null=True, blank=True)
    zxyfk = models.FloatField(_("专项应付款"), null=True, blank=True)
    yjfz = models.FloatField(_("预计负债"), null=True, blank=True)
    dysdsfz = models.FloatField(_("递延所得税负债"), null=True, blank=True)
    qtfldfz = models.FloatField(_("其他非流动负债"), null=True, blank=True)
    fldfzhj = models.FloatField(_("非流动负债合计"), null=True, blank=True)
    fzhj = models.FloatField(_("负债合计"), null=True, blank=True)
    sszbhgb = models.FloatField(_("实收资本或股本"), null=True, blank=True)
    zbgj = models.FloatField(_("资本公积"), null=True, blank=True)
    yygj = models.FloatField(_("盈余公积"), null=True, blank=True)
    zxcb = models.FloatField(_("专项储备"), null=True, blank=True)
    jkcg = models.FloatField(_("减库存股"), null=True, blank=True)
    bfxzb = models.FloatField(_("般风险准备"), null=True, blank=True)
    wfplr = models.FloatField(_("未分配利润"), null=True, blank=True)
    gsymgssyzqy = models.FloatField(_("归属于母公司所有者权益"), null=True, blank=True)
    ssgdqy = models.FloatField(_("少数股东权益"), null=True, blank=True)
    wbbbzsjc = models.FloatField(_("外币报表折算价差"), null=True, blank=True)
    fzcjyxmsydz = models.FloatField(_("非正常经营项目收益调整"), null=True, blank=True)
    syzqyhgdqyhj = models.FloatField(_("所有者权益或股东权益合计"), null=True, blank=True)
    fzhsyzhgdqyhj = models.FloatField(_("负债和所有者或股东权益合计"), null=True, blank=True)
    qtzhsy = models.FloatField(_("其他综合收益"), null=True, blank=True)
    dysyfldfz = models.FloatField(_("递延收益非流动负债"), null=True, blank=True)
    jsbfj = models.FloatField(_("结算备付金"), null=True, blank=True)
    cczj = models.FloatField(_("拆出资金"), null=True, blank=True)
    ffdkjdkldzc = models.FloatField(_("发放贷款及垫款流动资产"), null=True, blank=True)
    ysjrzc = models.FloatField(_("衍生金融资产"), null=True, blank=True)
    ysbf = models.FloatField(_("应收保费"), null=True, blank=True)
    ysfbzk = models.FloatField(_("应收分保账款"), null=True, blank=True)
    ysfbhtzbj = models.FloatField(_("应收分保合同准备金"), null=True, blank=True)
    mrfsjrzc = models.FloatField(_("买入返售金融资产"), null=True, blank=True)
    hfwcydsdzc = models.FloatField(_("划分为持有待售的资产"), null=True, blank=True)
    ffdkjdkfldzc = models.FloatField(_("发放贷款及垫款非流动资产"), null=True, blank=True)
    xzyyxjk = models.FloatField(_("向中央银行借款"), null=True, blank=True)
    xsckjtycf = models.FloatField(_("吸收存款及同业存放"), null=True, blank=True)
    crzj = models.FloatField(_("拆入资金"), null=True, blank=True)
    ysjrfz = models.FloatField(_("衍生金融负债"), null=True, blank=True)
    mchgjrzck = models.FloatField(_("卖出回购金融资产款"), null=True, blank=True)
    yfsxfjyj = models.FloatField(_("应付手续费及佣金"), null=True, blank=True)
    yffbzk = models.FloatField(_("应付分保账款"), null=True, blank=True)
    bxhtzbj = models.FloatField(_("保险合同准备金"), null=True, blank=True)
    dlmmzqk = models.FloatField(_("代理买卖证券款"), null=True, blank=True)
    dlcxzqk = models.FloatField(_("代理承销证券款"), null=True, blank=True)
    hfwcydsdfz = models.FloatField(_("划分为持有待售的负债"), null=True, blank=True)
    yjfzldfz = models.FloatField(_("预计负债流动负债"), null=True, blank=True)
    dysyldfz = models.FloatField(_("递延收益流动负债"), null=True, blank=True)
    qzyxgfldfz = models.FloatField(_("其中优先股非流动负债"), null=True, blank=True)
    yxzfldfz = models.FloatField(_("永续债非流动负债"), null=True, blank=True)
    cqyfzgxc = models.FloatField(_("长期应付职工薪酬"), null=True, blank=True)
    qtqygj = models.FloatField(_("其他权益工具"), null=True, blank=True)
    qzyxgsyzqy = models.FloatField(_("其中优先股所有者权益"), null=True, blank=True)
    yxzsyzqy = models.FloatField(_("永续债所有者权益"), null=True, blank=True)

    class Meta:
        verbose_name = '资产负债表'
        verbose_name_plural = '资产负债表'


class Cash(models.Model):
    """现金表"""
    organization_id = models.CharField(_("机构ID"), null=True, blank=True, max_length=32)
    organization_name = models.CharField(_("机构名称"), null=True, blank=True, max_length=128)
    announcement_date = models.DateField(_("公告日期"), null=True)
    begin_date = models.DateField(_("开始日期"), null=True)
    end_date = models.DateField(_("截止日期"), null=True)
    report_year = models.DateField(_("报告年度"), null=True)
    merge_type = models.CharField(_("合并类型"), null=True, blank=True, max_length=128)
    report_source = models.CharField(_("报表来源"), null=True, blank=True, max_length=128)
    xssptglwsddxj = models.FloatField(_("销售商品提供劳务收到的现金"), null=True, blank=True)
    sddsffh = models.FloatField(_("收到的税费返还"), null=True, blank=True)
    sdqtyjyhdygdxj = models.FloatField(_("收到其他与经营活动有关的现金"), null=True, blank=True)
    jyhdxjlrxj = models.FloatField(_("经营活动现金流入小计"), null=True, blank=True)
    gmspjslwzfdxj = models.FloatField(_("购买商品接受劳务支付的现金"), null=True, blank=True)
    zfgzgyjwzgzfdxj = models.FloatField(_("支付给职工以及为职工支付的现金"), null=True, blank=True)
    zfdgxsf = models.FloatField(_("支付的各项税费"), null=True, blank=True)
    zfqtyjyhdygdxj = models.FloatField(_("支付其他与经营活动有关的现金"), null=True, blank=True)
    jyhdxjlcxj = models.FloatField(_("经营活动现金流出小计"), null=True, blank=True)
    jyhdcsdxjllje = models.FloatField(_("经营活动产生的现金流量净额"), null=True, blank=True)
    shtzsddxj = models.FloatField(_("收回投资收到的现金"), null=True, blank=True)
    qdtzsysddxj = models.FloatField(_("取得投资收益收到的现金"), null=True, blank=True)
    czgdzcwxzchqtcqzcshdxjje = models.FloatField(_("处置固定资产无形资产和其他长期资产收回的现金净额"), null=True, blank=True)
    czzgsjqtyydwsddxjje = models.FloatField(_("处置子公司及其他营业单位收到的现金净额"), null=True, blank=True)
    sdqtytzhdygdxj = models.FloatField(_("收到其他与投资活动有关的现金"), null=True, blank=True)
    tzhdxjlrxj = models.FloatField(_("投资活动现金流入小计"), null=True, blank=True)
    gjgdzcwxzchqtcqzczfdxj = models.FloatField(_("购建固定资产无形资产和其他长期资产支付的现金"), null=True, blank=True)
    tzzfdxj = models.FloatField(_("投资支付的现金"), null=True, blank=True)
    zydkjzje = models.FloatField(_("质押贷款净增加额"), null=True, blank=True)
    qdzgsjqtyydwzfdxjje = models.FloatField(_("取得子公司及其他营业单位支付的现金净额"), null=True, blank=True)
    zfqtytzhdygdxj = models.FloatField(_("支付其他与投资活动有关的现金"), null=True, blank=True)
    tzhdxjlcxj = models.FloatField(_("投资活动现金流出小计"), null=True, blank=True)
    tzhdcsdxjllje = models.FloatField(_("投资活动产生的现金流量净额"), null=True, blank=True)
    xstzsddxj = models.FloatField(_("吸收投资收到的现金"), null=True, blank=True)
    qdjksddxj = models.FloatField(_("取得借款收到的现金"), null=True, blank=True)
    fxzqsddxj = models.FloatField(_("发行债券收到的现金"), null=True, blank=True)
    sdqtyczhdygdxj = models.FloatField(_("收到其他与筹资活动有关的现金"), null=True, blank=True)
    czhdxjlrxj = models.FloatField(_("筹资活动现金流入小计"), null=True, blank=True)
    chzwzfdxj = models.FloatField(_("偿还债务支付的现金"), null=True, blank=True)
    fpgllrhcflxzfdxj = models.FloatField(_("分配股利利润或偿付利息支付的现金"), null=True, blank=True)
    zfqtyczhdygdxj = models.FloatField(_("支付其他与筹资活动有关的现金"), null=True, blank=True)
    czhdxjlcxj = models.FloatField(_("筹资活动现金流出小计"), null=True, blank=True)
    czhdcsdxjllje = models.FloatField(_("筹资活动产生的现金流量净额"), null=True, blank=True)
    hlbddxjdyx = models.FloatField(_("汇率变动对现金的影响"), null=True, blank=True)
    qtyydxjdyx = models.FloatField(_("()其他原因对现金的影响"), null=True, blank=True)
    xjjxjdjwjzje = models.FloatField(_("现金及现金等价物净增加额"), null=True, blank=True)
    qcxjjxjdjwye = models.FloatField(_("期初现金及现金等价物余额"), null=True, blank=True)
    qmxjjxjdjwye = models.FloatField(_("期末现金及现金等价物余额"), null=True, blank=True)
    fz = models.FloatField(_("附注"), null=True, blank=True)
    jjlrdjwjyhdxjll = models.FloatField(_("将净利润调节为经营活动现金流量"), null=True, blank=True)
    jlr = models.FloatField(_("净利润"), null=True, blank=True)
    jzcjzzb = models.FloatField(_("加资产减值准备"), null=True, blank=True)
    gdzczjyqzczhscxswzczj = models.FloatField(_("固定资产折旧油气资产折耗生产性生物资产折旧"), null=True, blank=True)
    wxzctx = models.FloatField(_("无形资产摊销"), null=True, blank=True)
    cqdtfytx = models.FloatField(_("长期待摊费用摊销"), null=True, blank=True)
    czgdzcwxzchqtcqzcdss = models.FloatField(_("处置固定资产无形资产和其他长期资产的损失"), null=True, blank=True)
    gdzcbfss = models.FloatField(_("固定资产报废损失"), null=True, blank=True)
    gyjzbdss = models.FloatField(_("公允价值变动损失"), null=True, blank=True)
    cwfy = models.FloatField(_("财务费用"), null=True, blank=True)
    tzss = models.FloatField(_("投资损失"), null=True, blank=True)
    dysdszcjs = models.FloatField(_("递延所得税资产减少"), null=True, blank=True)
    dysdsfzzj = models.FloatField(_("递延所得税负债增加"), null=True, blank=True)
    chdjs = models.FloatField(_("存货的减少"), null=True, blank=True)
    jyxysxmdjs = models.FloatField(_("经营性应收项目的减少"), null=True, blank=True)
    jyxyfxmdzj = models.FloatField(_("经营性应付项目的增加"), null=True, blank=True)
    qt = models.FloatField(_("其他"), null=True, blank=True)
    jyhdcsdxjllje_2 = models.FloatField(_("经营活动产生的现金流量净额"), null=True, blank=True)
    bsjxjszdzdtzhczhd = models.FloatField(_("不涉及现金收支的重大投资和筹资活动"), null=True, blank=True)
    zwzwzb = models.FloatField(_("债务转为资本"), null=True, blank=True)
    nndqdkzhgszq = models.FloatField(_("年内到期的可转换公司债券"), null=True, blank=True)
    rzzrgdzc = models.FloatField(_("融资租入固定资产"), null=True, blank=True)
    xjjxjdjwjbdqk = models.FloatField(_("现金及现金等价物净变动情况"), null=True, blank=True)
    xjdqmye = models.FloatField(_("现金的期末余额"), null=True, blank=True)
    jxjdqcye = models.FloatField(_("减现金的期初余额"), null=True, blank=True)
    jxjdjwdqmye = models.FloatField(_("加现金等价物的期末余额"), null=True, blank=True)
    jxjdjwdqcye = models.FloatField(_("减现金等价物的期初余额"), null=True, blank=True)
    jqtyydxjdyx = models.FloatField(_("加其他原因对现金的影响"), null=True, blank=True)
    xjjxjdjwjzje_2 = models.FloatField(_("现金及现金等价物净增加额"), null=True, blank=True)
    khckhtycfkxjzje = models.FloatField(_("客户存款和同业存放款项净增加额"), null=True, blank=True)
    xzyyxjkjzje = models.FloatField(_("向中央银行借款净增加额"), null=True, blank=True)
    xqtjrjgcrzjjzje = models.FloatField(_("向其他金融机构拆入资金净增加额"), null=True, blank=True)
    sdybxhtbfqddxj = models.FloatField(_("收到原保险合同保费取得的现金"), null=True, blank=True)
    sdzbxywxjje = models.FloatField(_("收到再保险业务现金净额"), null=True, blank=True)
    bhcjjtzkjzje = models.FloatField(_("保户储金及投资款净增加额"), null=True, blank=True)
    czygyjzjlqqbdjrdqsydjrzcjzje = models.FloatField(_("处置以公允价值计量且其变动计入当期损益的金融资产净增加额"), null=True, blank=True)
    sqlxsxfjyjdxj = models.FloatField(_("收取利息手续费及佣金的现金"), null=True, blank=True)
    crzjjzje = models.FloatField(_("拆入资金净增加额"), null=True, blank=True)
    hgywzjjzje = models.FloatField(_("回购业务资金净增加额"), null=True, blank=True)
    khdkjdkjzje = models.FloatField(_("客户贷款及垫款净增加额"), null=True, blank=True)
    cfzyyxhtykxjzje = models.FloatField(_("存放中央银行和同业款项净增加额"), null=True, blank=True)
    zfybxhtpfkxdxj = models.FloatField(_("支付原保险合同赔付款项的现金"), null=True, blank=True)
    zflxsxfjyjdxj = models.FloatField(_("支付利息手续费及佣金的现金"), null=True, blank=True)
    zfbdhldxj = models.FloatField(_("支付保单红利的现金"), null=True, blank=True)
    qzzgsxsssgdtzsddxj = models.FloatField(_("其中子公司吸收少数股东投资收到的现金"), null=True, blank=True)
    qzzgszfgssgddgllr = models.FloatField(_("其中子公司支付给少数股东的股利利润"), null=True, blank=True)
    tzxfdcdzjjtx = models.FloatField(_("投资性房地产的折旧及摊销"), null=True, blank=True)

    class Meta:
        verbose_name = '现金表'
        verbose_name_plural = '现金表管理'
