version: '2'

services:
  postgres:
    image: postgres:9.6
    networks:
      - default
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/postgres_data:/var/lib/postgresql/data
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "5"

  redis:
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - ./docker_data/redis_data:/data
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "2M"

  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      # - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - ./docker_data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker_data/elasticsearch_data:/usr/share/elasticsearch/data
      - ./docker_data/elasticsearch_plugins:/usr/share/elasticsearch/plugins/
    ports:
      - 9200:9200
    networks:
      - default
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "5"

  elasticsearch_head:
    image: mobz/elasticsearch-head:5
    ports:
      - 9100:9100
    networks:
      - default
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "2M"
        max-file: "5"