# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_profile_favorites_list'),
        ('rest_api', '0004_auto_20170921_1116'),
    ]

    operations = [
    ]
