# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-25 11:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_merge_20170925_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=[], size=None),
        ),
    ]
