# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_userprofile_favorites_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='attachment_images',
            field=models.TextField(default=''),
        ),
    ]
