# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_researchreport_attachment_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_images',
            field=models.TextField(blank=True, default=''),
        ),
    ]
