# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-20 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20171019_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_content',
            field=models.TextField(blank=True, default='', max_length=10000000),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_images',
            field=models.TextField(blank=True, default='', max_length=10000000),
        ),
    ]
