# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_auto_20171020_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreport',
            name='article_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_images',
            field=models.TextField(blank=True, default=''),
        ),
    ]
