# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_auto_20171023_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='organization',
        ),
        migrations.AddField(
            model_name='author',
            name='analyst_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='comp_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='education',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='expire_date',
            field=models.DateTimeField(default='1949-10-1'),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='grant_date',
            field=models.DateTimeField(default='1949-10-1'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo_path',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='sec_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
