# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-26 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_auto_20171026_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='analyst_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='comp_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo_path',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
