# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_auto_20171026_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='table_raw_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='authors',
            field=models.ManyToManyField(blank=True, to='rest_api.Author'),
        ),
    ]
