# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-30 03:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_auto_20171027_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_images',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='table_raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
