# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-30 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_auto_20171030_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreport',
            name='article_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='article_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='article_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='researchreport',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
