# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0019_auto_20171030_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='attachment_words',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
