# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0020_researchreport_attachment_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='pages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
