# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0021_researchreport_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchreport',
            name='attachment_images',
        ),
    ]
