# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_researchreport_attachment_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='hash',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
