# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_researchreport_table_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='stocks_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
