# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 10:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_researchreport_table_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchreport',
            name='attachment_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True), blank=True, default=[], null=True, size=None),
        ),
    ]
