# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0027_researchreport_stocks_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=10)),
                ('revenue', models.FloatField(null=True)),
                ('net_income', models.FloatField(null=True)),
                ('net_income_shareholders', models.FloatField(null=True)),
                ('revenue_cost', models.FloatField(null=True)),
                ('operating_income', models.FloatField(null=True)),
                ('total_income', models.FloatField(null=True)),
                ('eps_diluted', models.FloatField(null=True)),
                ('eps_basic', models.FloatField(null=True)),
                ('short_term_debt', models.FloatField(null=True)),
                ('operating_cashflow', models.FloatField(null=True)),
                ('investing_cashflow', models.FloatField(null=True)),
                ('financing_cashflow', models.FloatField(null=True)),
                ('cash_and_equivalents', models.FloatField(null=True)),
                ('unit_multiplier', models.FloatField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='rest_api.ResearchReport')),
            ],
        ),
    ]
