# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-12 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0028_estimate'),
        ('rest_api', '0027_auto_20171112_1013'),
    ]

    operations = [
    ]
