# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0029_merge_20171112_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='uuid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
