# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0030_author_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('openid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unionid', models.CharField(default='', max_length=50, null=True)),
                ('nickname', models.CharField(default='', max_length=50, null=True)),
                ('sex', models.IntegerField(default=1)),
                ('language', models.CharField(default='en', max_length=5)),
                ('city', models.CharField(default='', max_length=5)),
                ('province', models.CharField(default='', max_length=5)),
                ('country', models.CharField(default='', max_length=5)),
                ('headimgurl', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
