# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0031_wechatuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='language',
            field=models.CharField(default='en', max_length=200),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='province',
            field=models.CharField(default='', max_length=200),
        ),
    ]
