# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-18 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_finance_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': '资产负债表', 'verbose_name_plural': '资产负债表'},
        ),
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name': '现金表', 'verbose_name_plural': '现金表管理'},
        ),
        migrations.AlterModelOptions(
            name='profit',
            options={'verbose_name': '利润表', 'verbose_name_plural': '利润表管理'},
        ),
    ]
